---
# This playbook prints a simple debug message
- name: Test morpheus variables 
  hosts: all
  gather_facts: yes
  become: yes
  become_user: root
  become_method: sudo
  connection: local

  tasks:
  - name: gather facts
    debug:
      msg: Hello, world!
