---

- name: Add a user
  #hosts: "{{ morhost }}"
  hosts: all
  gather_facts: false
  tasks:
    - name: Add User
      win_user:
        name: "{{ morpheus['customOptions']['user_name']}}"
        password: "{{ lookup('cypher','secret=secret/testuser') }}"
        state: present
