---
- name: Download Diruse
  hosts: windows
  tasks:
    - name: Define variable
      win_get_url:
        url: " {{ windows_repo.url }}/diruse/{{ item.key }} "
        dest: "C:\\windows\\{{ item.key }}"
        checksum: " {{ item.value }} "
        checksum_algorithm: sha256
        force: True
