---
- name: Post Build Configuration for Windows Servers
  hosts: windows
  gather_facts: false
  tasks:
    - name: Download ndtrack.ps1
      win_get_url:
        url: "{{ windows_repo.url }}/flexera2018R2/ndtrack.ps1"
        dest: "C:\\temp\\ndtrack.ps1"
        force: True
    - name: Install Flexnet Inventory Agent from msi
      win_package:
        path: "{{ windows_repo.url }}/flexera2018R2/FlexNet_Inventory_Agent.msi"
        product_id: '{7A62397D-66E2-41C4-BFFC-2EBB38D16790}'
        arguments: /qn /norestart ALLUSERS=1 REBOOT=ReallySuppress /L*v c:\temp\FlexNet_Inventory_Agent_Installation.log
        state: present
    - name: Trigger ndtrack.ps1
      win_shell: "C:\\temp\\ndtrack.ps1"
      args:
        chdir: C:\\temp
