---
- name: Print some debug information
  hosts: all
  gather_facts: true
  vars: 
    hostname: {{ morpheus.instance.hostname }}
  tasks:
    - name: Print some debug information
      debug: 
        hostname: "{{ hostname }}"
