---
- name: Print some debug information
  hosts: all
  gather_facts: true
  tasks:
    - name: Print some jinja variable
      vars: 
        msg: |
            hostname: {{ ansible_hostname | lower }}
            DC: {{ hostname.stdout[0:4] | lower  }}
            country: {{ hostname.stdout[0:2] | lower }}
      debug: 
        msg: "{{ msg.split('\n') }}"       
      tags: debug_info
