---
- name: Print some debug information
  hosts: all
  gather_facts: true
  tasks:
    - name: Print vars variable information
      debug: 
        var: hostvars[inventory_hostname]  
      tags: debug_info
