---
- name: Print some debug information
  hosts: all
  gather_facts: true
  tasks:
    - name: Gather vars variable information
      vars:
        hostname: "{{ vars.morpheus.instance.hostname }}"
    - name: Print vars variable information
      debug: 
        hostname: "{{ hostname }}" 
