---
- name: Print some debug information
  hosts: windows
  tasks:
    - name: Define variable
      debug:
        msg: "{{ item }} is an environment variable"
      with_items: "{{ windows_diruse.files.items() }}"
