---
- name: Print some debug information
  hosts: all
  gather_facts: false
  tasks:
    - name: Print some debug information
      vars: 
        msg: |
            User: {{ MSSQL.REGIONSERVICEACCOUNT.amer.USER }}
            Password: {{ MSSQL.REGIONSERVICEACCOUNT.amer.PW }}
      debug: 
        msg: "{{ msg.split('\n') }}"       
      tags: debug_info
    - name: Print some jinja variable
      shell: echo $HOSTNAME
      register: hostname
      {% set dc = {{ hostname }}[0:4]|lower %}
      {% set country = dc[0:2] %}
      vars: 
        msg: |
            DC: {{ dc }}
            country: {{ country }}
      debug: 
        msg: "{{ msg.split('\n') }}"       
      tags: debug_info
