---
- name: Print some debug information
  hosts: all
  gather_facts: true
  tasks:
    - name: Print some jinja variable
      vars: 
        msg: |
            hostname: {{ ansible_hostname | lower }}
            DC: {{ ansible_hostname[0:4] | lower  }}
            country: {{ ansible_hostname[0:2] | lower }}
            
      debug: 
        hostname: "{{ ansible_hostname | lower }}"
        DC: "{{ ansible_hostname[0:4] | lower  }}"
        country: "{{ ansible_hostname[0:2] | lower }}"
      tags: debug_info 
