---
- name: copy diruse
  hosts: windows
  gather_facts: false
  tasks:
    - name: Create sysinternals directory
      win_file:
        path: c:\IT\SysInternals
        state: directory
    - name: Download sysiternals files
      win_get_url:
        url: "{{ windows_repo.url }}/SysInternals-suite/{{ item.key }}"
        dest: "c:\\it\\SysInternals\\{{ item.key }}"
        checksum: "{{ item.value }}"
        checksum_algorithm: sha256
        force: True
      loop: "{{ lookup('dict', sysinternals.files) }}"
