---
- name: Print some debug information
  hosts: all
  gather_facts: true
  tasks:
    - name: Define variable
      vars: 
        hostname: "{{ morpheus['instance']['hostname'] }}"
    - debug: msg="{{ hostname | lower  }}"
