---
- name: copy diruse
  hosts: windows
  gather_facts: false
  tasks:
    - name: Download diruse files
      win_get_url:
        url: "{{ windows_repo.url }}/diruse/{{ item.key }}"
        dest: "C:\\windows\\{{ item.key }}"
        checksum: "{{ item.value }}"
        checksum_algorithm: sha256
        force: True
      with_dict: "{{ lookup('dict', windows_diruse.files) }}"
