---
- name: Print some debug information
  hosts: all
  gather_facts: false
  tasks:
    - name: Print some debug information
      vars: 
        msg: |
            Environment Variables ("environment"):
            --------------------------------
            {{ environment | to_nice_json }}
      debug: 
        msg: "{{ msg.split('\n') }}"       
      tags: debug_info
