---
- name: Print some debug information
  hosts: windows
  tasks:
    - name: Define variable
      debug:
        msg: "key {{ item.key }} has an value of {{ item.value }}"
      loop: "{{ lookup('dict', "{{ windows_diruse.files.items() }}") }}"
