---
- name: Print some debug information
  hosts: all
  gather_facts: true
  tasks:
    - name: Print some jinja variable
      vars: 
        hostname: {{ ansible_hostname | lower }}
        DC: {{ ansible_hostname[0:4] | lower  }}
        country: {{ ansible_hostname[0:2] | lower }}
            
      debug: 
        hostname: "{{ hostname }}"
        DC: "{{ DC }}"
        country: "{{ country }}"
      tags: debug_info 
