---
- name: copy diruse
  hosts: windows
  gather_facts: false
  tasks:
    - name: Create Desktop Info folder
      win_file:
        path: 'C:\Program Files (x86)\DesktopInfo'
        state: directory
    - name: Stop Desktop Info Process if runs
      win_shell: |
        Get-Process desktopinfo -ErrorAction SilentlyContinue | Stop-Process -Force -ErrorAction SilentlyContinue
    - name: Download desktop info files
      win_get_url:
        url: "{{ windows_repo.url }}/DesktopInfo/{{ item.key }}"
        dest: "C:\\Program Files (x86)\\DesktopInfo\\{{ item.key }}"
        checksum: "{{ item.value }}"
        checksum_algorithm: sha256
        force: True
      loop: "{{ lookup('dict', windows_desktopinfo.files) }}"
