- name: Change CD-Rom Drive letter to Z
  hosts: windows
  gather_facts: false
  tasks:
    - name: Change CD-Rom Drive letter to Z
      win_shell: |
        $CDDrive = Get-WmiObject win32_volume | where {$_.DriveType -eq 5}
        if ($CDDrive  -ne $null) {
            $CDDrive.DriveLetter = "Z:";
            $CDDrive.put()
        }
