---
- name: Print some debug information
  hosts: all
  vars: 
    files: "{{ windows_diruse.files.items()  }}"
    repopath: "{{ windows_repo.url }}"
  tasks:
    - name: Define variable
      - debug: msg="{{ lookup('env','HOME') }} is an environment variable"
