---
- name: Print some debug information
  hosts: windows
  tasks:
    - name: Define variable
      debug:
        msg: "repo path is {{ windows_repo.url }} and name {{ item.key }} has an sha value of {{ item.value }}"
      with_dict: "{{ windows_diruse.files }}"
