---
- name: Print some debug information
  hosts: windows
  tasks:
    - name: Define variable
      debug:
        msg: "name {{ item.name }} has an sha value of {{ item.sha }}"
      with_items: "{{ windows_diruse.files }}"
