- name: Extend C Drive
  hosts: windows
  gather_facts: false
  tasks:
    - name: Extend C Drive
      win_shell: |
        $cDriveSupportSize = $(Get-PartitionSupportedSize -DriveLetter "C").sizeMax
        $cDriveSize = $(Get-Partition -DriveLetter "C").size
        try{
            if($cDriveSupportSize -gt $cDriveSize)
            {
                resize-Partition -Size $cDriveSupportSize -DriveLetter "C" -ErrorAction stop
            }
        }
        catch{}
