---
- name: Print some debug information
  hosts: all
  gather_facts: false
  tasks:
    - name: Display all variables/facts known for a host
      debug: 
        var: hostvars[inventory_hostname]  | to_nice_json     
      tags: debug_info
