---
- name: Print some debug information
  hosts: all
  gather_facts: false
  tasks:
    - name: Print some debug information
      vars: 
        msg: |
            User: {{ MSSQL.REGIONSERVICEACCOUNT.amer.USER }}
            Password: {{ MSSQL.REGIONSERVICEACCOUNT.amer.PW }}
      debug: 
        msg: "{{ msg.split('\n') }}"       
      tags: debug_info
    - name: Print some jinja variable
      vars: 
        msg: |
            nodename: {{ ansible_facts['ansible_all_ipv4_addresses'] }}
      debug: 
        msg: "{{ msg.split('\n') }}"       
      tags: debug_info
    - setup:
      gather_subset: [network]

    - debug: msg={{ ansible_all_ipv4_addresses }}
