---
- name: Print some debug information
  hosts: all
  gather_facts: true
  tasks:
    - name: Define variable
      vars: 
        hostname: {{ ansible_hostname | lower }}
        DC: {{ ansible_hostname[0:4] | lower  }}
        country: {{ ansible_hostname[0:2] | lower }}
            
    - name: Print variable
      debug: 
        msg: "{{ hostname }},{{ DC }},{{ country }}"       
      tags: debug_info
