---
- name: Print some debug information
  hosts: all
  gather_facts: true
  tasks:
    - name: Define variable
      vars: 
        hostname: "{{ ansible_hostname | lower }}"
    - debug: msg="{{ hostname | lower  }}"
    - debug: msg="{{ ansible_hostname[0:4] | lower  }}"
    - debug: msg="{{ ansible_hostname[0:2] | lower  }}"
