---
- name: Print some debug information
  hosts: all
  gather_facts: false
  tasks:
    - name: Print some debug information
      vars: 
        msg: |
            pulprepo: {{ windows_repo.url }}
      debug: 
        msg: "{{ msg.split('\n') }}"       
      tags: debug_info
