---
- name: Print some debug information
  hosts: all
  vars: 
    hostname: "{{ morpheus['instance']['hostname']  }}"
  tasks:
    - name: Define variable
      debug:
        {% for name, hash in windows_diruse.files.items() %}
        msg: "{{ name | lower  }}"
        {% endfor %}
