---
- name: Print some debug information
  hosts: all
  gather_facts: true
  tasks:
    - name: Print some jinja variable
      debug: 
        hostname: "{{ ansible_hostname }}"       
      tags: debug_info 
