---
- name: enable AutomaticManagedPagefile
  hosts: all
  gather_facts: false
  tasks:
    - name: Remove all current pagefiles, enable AutomaticManagedPagefile and query at the end  
      win_pagefile:
        automatic: yes
